# Generated by Django 5.1 on 2024-08-19 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_buy_price_drug_base_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_minutes', models.PositiveIntegerField()),
                ('from_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_zone', to='game.zone')),
                ('to_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_zone', to='game.zone')),
            ],
            options={
                'unique_together': {('from_zone', 'to_zone')},
            },
        ),
    ]
