# Generated by Django 5.1 on 2024-08-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_traveltime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='item',
        ),
        migrations.RemoveField(
            model_name='traveltime',
            name='time_minutes',
        ),
        migrations.AddField(
            model_name='traveltime',
            name='travel_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
