# Generated by Django 5.1 on 2024-08-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_drug_zones_alter_drug_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drug',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
