# Generated by Django 5.1 on 2024-08-19 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.drug')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.zone')),
            ],
            options={
                'unique_together': {('drug', 'zone', 'price_type')},
            },
        ),
    ]
