# Generated by Django 5.1 on 2024-08-19 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_drugprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TravelTime',
        ),
    ]
