# Generated by Django 5.1 on 2024-08-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_ab'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AB',
        ),
    ]
